[versions]
kotlin = "2.3.0"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = { strictly = "0.7.1" }

compose = "1.10.0"

java = "18"

mmrpc = "0.5.0-beta.4"
extkt = "0.1.5"

lsafer-compose-simplenav = "0.0.6-rc.2"

filekit = "0.12.0"

# ANDROID
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"

androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.6"

material3-adaptive = "1.2.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }

gradleup-tapmoc = { id = "com.gradleup.tapmoc", version = "0.4.0" }

[libraries]

##### Official Dependencies #####

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

##### Internal Dependencies #####

mmrpc-definition = { module = "org.cufy.mmrpc:mmrpc-definition", version.ref = "mmrpc" }

extkt-json = { module = "org.cufy.extkt:extkt-json", version.ref = "extkt" }

lsafer-compose-simplenav = { module = "net.lsafer.compose-simplenav:compose-simplenav", version.ref = "lsafer-compose-simplenav" }

##### Community Dependencies #####

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }

mikepenz-markdownCompose = { module = "com.mikepenz:multiplatform-markdown-renderer", version = "0.39.1" }
mikepenz-markdownCompose-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version = "0.39.1" }

touchlab-kermit = { module = "co.touchlab:kermit", version = "2.0.8" }
harawata-appdirs = { module = "net.harawata:appdirs", version = "1.5.0" }

##### ANDROID Dependencies #####

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

##### ANDROID (JB) Dependencies #####

androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }
